dist: trusty
sudo: require

language: cpp
compiler: clang++

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - cmake-data
      - cmake
      

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - CXX=/usr/bin/clang++-5.0
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j 8
  - ctest -V
  - make clean
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j 8