name: C/C++ CI

on: [push]

jobs:
  debug-build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir build
    - run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B ./build
    - run: make --directory ./build -j
    
  test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir build
    - run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B ./build
    - run: make --directory ./build -j
    - run: make test -C ./build ARGS='--output-on-failure'

  release-build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir build
    - run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./build
    - run: make --directory ./build -j
